### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by HitarthBharad** [INFO-526-F24/project-01-Pacman#3]
The following is the peer review of the project proposal by VIZards. The team members that participated in this review are 

1. Hitarth Bharad - @HitarthBharad
2. Ashwini Jannu - @AshwiniJannu
3. Mridula Kalaiselvan -@mridula237
4. Lekhashree Honnavalli Jayarama -@lekhashree03
5. Dhawal Gajwe - @billDhawal
6. Hardik Chemburkar - @TRENCHhardik2042

**- Describe the goal of the project.**
Project aims to determine the seasonal sales patterns, high-value client group and the effect of discounts by examining parameters. The knowledge acquired will contribute to comprehension of customer decision-making processes and the effects of various sales tactics on performance in various contexts.

**- Describe the data used or collected.**
Dataset has been taken from  Kaggle. This dataset  includes transaction records from different shopping malls and regions, designed to give a broad overview of consumer habits, sales patterns, and seasonal trends in e-commerce.

**- Describe how the research question will be answered, e.g. what approaches / methods will be used.**
_Question 1:_ How Do Seasonal Trends Affect Sales Performance Across Different Categories, Malls, and Payment Methods?
_Approach_:  By Investigating the impact of seasonal fluctuations on sales across product categories and locations. 

_Question 2:_ What Are the Relationships Between Discounted Prices, Sales Volumes, and Profit Margins in Different Shopping Malls and Product Categories?
_Approach_: By examining the influence of discounts on sales volumes and profit margins, analyzing correlations across product categories and shopping malls. 

**- Is there anything that is unclear from the proposal?**
Analysis summary should have been elaborated. 

**- Provide constructive feedback on how the team might be able to improve their project.**
1. Relationship between different categorical variables such as season and payment methods could have elaborated in the question and analysis 
7. Tabular data analysis could have been provided.

**- What aspect of this project are you most interested in and would like to see highlighted in the presentation.**
The data is collected from 2006 to 2024 time period. The change in the sales trend can raise interesting observations like customer decision-making processes and the effects of various sales tactics on performance in various contexts.

**- Provide constructive feedback on any issues with file and/or code organization.**

1. To enhance the readability and clarity of research questions, consider using the numbered points instead of using the bullet points and remove the capitalization of every word.
2. Analysis plan could have been more elaborated to answer detailed planned execution summary.

**- (Optional) Any further comments or feedback?**
Overall proposal documentation is well structured.

**Comment by DevashreePawar** [comment]
Thank you for the feedback
